language: bash
services: docker
sudo: required

env:
  - VERSION=php/5.3/vanilla-apache/
  - VERSION=php/5.3/apache/
  - VERSION=php/5.3/vanilla/
  - VERSION=php/5.3/
  - VERSION=php/5.4/
  - VERSION=php/5.5/
  - VERSION=php/
  - VERSION=php/7.0/
  - VERSION=php/7.1/

before_script:
  - cd $VERSION

script:
  - docker build .

after_script:
  - docker images
